using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.Drawing.Text;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Aly.Core;

namespace Aly.ArtBuild
{
    /// <summary>
    /// art/&lt;pet&gt;/outfits.txt: [id], name = …, coat = yes|no, then "paletteKey = rrggbb" lines.
    /// Checked against the palette and written to assets/&lt;pet&gt;/outfits.txt with palette
    /// indices, which is what the app reads (Aly.Core.Wardrobe).
    /// </summary>
    sealed class OutfitSource
    {
        public string Id;
        public string Name;
        public bool Coat;
        public readonly List<KeyValuePair<char, uint>> Colors = new List<KeyValuePair<char, uint>>();

        public static List<OutfitSource> Load(string path, Palette pal, List<string> warnings)
        {
            var list = new List<OutfitSource>();
            OutfitSource cur = null;
            string[] lines = File.ReadAllLines(path, Encoding.UTF8);
            for (int i = 0; i < lines.Length; i++)
            {
                string line = Palette.StripComment(lines[i]);
                if (line.Length == 0) continue;
                if (line.StartsWith("[") && line.EndsWith("]"))
                {
                    cur = new OutfitSource();
                    cur.Id = line.Substring(1, line.Length - 2).Trim();
                    cur.Name = cur.Id;
                    if (!System.Text.RegularExpressions.Regex.IsMatch(cur.Id, "^[a-z][a-z0-9_]*$"))
                        throw new ArtException(path, i + 1, "outfit ids are lower-case words");
                    if (list.Any(o => o.Id == cur.Id)) throw new ArtException(path, i + 1, "duplicate outfit " + cur.Id);
                    list.Add(cur);
                    continue;
                }
                int eq = line.IndexOf('=');
                if (eq <= 0 || cur == null) throw new ArtException(path, i + 1, "expected [id] or key = value");
                string key = line.Substring(0, eq).Trim(), value = line.Substring(eq + 1).Trim();
                if (key == "name") { cur.Name = value; continue; }
                if (key == "coat") { cur.Coat = value == "yes"; continue; }
                if (key.Length != 1 || pal.IndexOf(key[0]) <= 0) throw new ArtException(path, i + 1, "'" + key + "' is not a palette key");
                uint color;
                if (value.Length != 6 || !uint.TryParse(value, NumberStyles.HexNumber, CultureInfo.InvariantCulture, out color))
                    throw new ArtException(path, i + 1, "colour must be rrggbb");
                if (cur.Colors.Any(c => c.Key == key[0])) throw new ArtException(path, i + 1, "'" + key + "' set twice");
                cur.Colors.Add(new KeyValuePair<char, uint>(key[0], 0xFF000000u | color));
            }
            if (list.Count == 0) throw new ArtException(path, 1, "no outfits");

            // Every outfit should say something about the same slots, and the first one is the
            // palette's own colours (that is what the atlas is drawn with).
            var slots = new HashSet<char>(list.SelectMany(o => o.Colors.Select(c => c.Key)));
            foreach (OutfitSource o in list)
            {
                var missing = slots.Where(k => !o.Colors.Any(c => c.Key == k)).ToList();
                if (missing.Count > 0) warnings.Add("outfit " + o.Id + " leaves out " + new string(missing.ToArray()));
            }
            foreach (var c in list[0].Colors)
            {
                if (pal.Colors[pal.IndexOf(c.Key)] != c.Value)
                    warnings.Add("outfit " + list[0].Id + " (the default) differs from palette.txt at '" + c.Key + "'");
            }
            return list;
        }

        public static void Write(string path, List<OutfitSource> list, Palette pal)
        {
            var sb = new StringBuilder();
            sb.Append("# Generated by ArtBuild from art/<pet>/outfits.txt — palette index = AARRGGBB. Do not edit.\r\n");
            foreach (OutfitSource o in list)
            {
                sb.Append("\r\n[").Append(o.Id).Append("]\r\n");
                sb.Append("name = ").Append(o.Name).Append("\r\n");
                sb.Append("coat = ").Append(o.Coat ? "yes" : "no").Append("\r\n");
                foreach (var c in o.Colors)
                    sb.Append(pal.IndexOf(c.Key).ToString(CultureInfo.InvariantCulture)).Append(" = ").Append(c.Value.ToString("X8", CultureInfo.InvariantCulture)).Append("\r\n");
            }
            File.WriteAllText(path, sb.ToString(), new UTF8Encoding(false));
        }

        public uint[] Apply(uint[] palette, Palette pal)
        {
            var p = (uint[])palette.Clone();
            foreach (var c in Colors) p[pal.IndexOf(c.Key)] = c.Value;
            return p;
        }
    }

    static partial class PreviewOutfits
    {
        /// <summary>_outfits.png: every outfit on the idle pose (the coat ones on their coat look).</summary>
        public static void Write(string dir, List<OutfitSource> outfits, Palette pal, Func<OutfitSource, Atlas> atlasFor, int zoom)
        {
            const int gap = 10, label = 22;
            int n = outfits.Count;
            Atlas first = atlasFor(outfits[0]);
            int cw = first.CanvasWidth * zoom, ch = first.CanvasHeight * zoom;
            int W = n * (cw + gap) + gap, H = ch + label + 2 * gap;
            int[] img = Preview.NewImage(W, H);
            for (int i = 0; i < n; i++)
            {
                Atlas atlas = atlasFor(outfits[i]);
                AtlasClip idle = atlas.GetClip("idle");
                if (idle == null) continue;
                uint[] keep = atlas.Palette;
                atlas.Palette = outfits[i].Apply(keep, pal);
                try
                {
                    byte[] canvas = new FrameFlattener(atlas).Flatten(idle.Frames[0]);
                    int x0 = gap + i * (cw + gap);
                    for (int y = 0; y < atlas.CanvasHeight; y++)
                        for (int x = 0; x < atlas.CanvasWidth; x++)
                        {
                            int c = canvas[y * atlas.CanvasWidth + x];
                            if (c == 0) continue;
                            for (int yy = 0; yy < zoom; yy++)
                                for (int xx = 0; xx < zoom; xx++)
                                    img[(gap + y * zoom + yy) * W + x0 + x * zoom + xx] = (int)atlas.Palette[c];
                        }
                }
                finally
                {
                    atlas.Palette = keep;
                }
            }
            using (Bitmap bmp = Preview.ToBitmap(img, W, H))
            using (Graphics g = Graphics.FromImage(bmp))
            using (var font = new Font("Microsoft YaHei UI", 9f))
            {
                g.TextRenderingHint = TextRenderingHint.AntiAliasGridFit;
                for (int i = 0; i < n; i++)
                {
                    string text = outfits[i].Name;
                    SizeF s = g.MeasureString(text, font);
                    g.DrawString(text, font, Brushes.Black, gap + i * (cw + gap) + (cw - s.Width) / 2, gap + ch + 2);
                }
                bmp.Save(Path.Combine(dir, "_outfits.png"), ImageFormat.Png);
            }
        }
    }
}
